services:
  sd_telegram_bot:
    build: .
    container_name: sd_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:8010:8010"
